/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'vicky' at '12/4/16 9:23 PM' with Gradle 2.14.1
 *
 * @author vicky, @date 12/4/16 9:23 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
